-- -----------------------------------------------------
-- Projet BDD2 Partie 2
-- ANDREOLLI Justine 
-- HASHEMI Seyedali
-- TD2 TP3
-- -----------------------------------------------------
DROP FUNCTION calculate_weekly_points;
DROP PROCEDURE move_tasks;
DROP FUNCTION are_tasks_similar;
DROP FUNCTION are_users_similar;
DROP FUNCTION Procedure3AfficheTachesSuggerees;
DROP PROCEDURE AfficherTableScoreCategorieTache;
DROP PROCEDURE generate_individual_tasks;

ALTER TABLE Comporte DROP CONSTRAINT FK_COMPORTE_REFSCORE_CATEGORIE;
ALTER TABLE Comporte DROP CONSTRAINT FK_COMPORTE_PROG;
ALTER TABLE Contient DROP CONSTRAINT FK_CONTIENT_REFLISTE;
ALTER TABLE Contient DROP CONSTRAINT FK_CONTIENT_PROJET;
ALTER TABLE Depend_de DROP CONSTRAINT FK_DEPEND_RETACHE1;
ALTER TABLE Depend_de DROP CONSTRAINT FK_DEPEND_RETACHE2;
ALTER TABLE Est_assigne DROP CONSTRAINT FK_EST_ASSIGNE_REFTACHE;
ALTER TABLE Est_assigne DROP CONSTRAINT FK_EST_ASSIGNE_REFUTILISATEUR;
ALTER TABLE Liste_tache DROP CONSTRAINT FK_LISTETACHE_REFUTILISATEUR;
ALTER TABLE Liste_tache DROP CONSTRAINT FK_TACHE_CATEGORIE_lt;

ALTER TABLE Tache DROP CONSTRAINT FK_TACHE_REF;
ALTER TABLE Tache DROP CONSTRAINT FK_TACHE_REFUTILISATEUR;
ALTER TABLE Tache DROP CONSTRAINT FK_TACHE_REFPERIODICITE;
ALTER TABLE Tache DROP CONSTRAINT CK_PRIORITE_T;
ALTER TABLE Tache DROP CONSTRAINT FK_TACHE_CATEGORIE_t;
ALTER TABLE Tache DROP CONSTRAINT CK_TACHE_STATUT;

ALTER TABLE Tache_fini DROP CONSTRAINT FK_TACHE_FINI_REF ;
ALTER TABLE Tache_fini DROP CONSTRAINT FK_TACHE_FINI_REF_REFUTILISATEUR ;
ALTER TABLE Tache_fini DROP CONSTRAINT FK_TACHE_FINI_REFPERIODICITE ;
ALTER TABLE Tache_fini DROP CONSTRAINT CK_PRIORITE_F;
ALTER TABLE Tache_fini DROP CONSTRAINT FK_TACHE_CATEGORIE_f;
ALTER TABLE Tache_fini DROP CONSTRAINT CK_FINI_STATUT;

ALTER TABLE Tache_en_cours DROP CONSTRAINT FK_TACHE_EN_COURS_REF ;
ALTER TABLE Tache_en_cours DROP CONSTRAINT FK_TACHE_EN_COURS_REFUTILISATEUR ;
ALTER TABLE Tache_en_cours DROP CONSTRAINT FK_TACHE_EN_COURS_REFPERIODICITE ;
ALTER TABLE Tache_en_cours DROP CONSTRAINT CK_PRIORITE_C;
ALTER TABLE Tache_en_cours DROP CONSTRAINT FK_TACHE_CATEGORIE_c;
ALTER TABLE Tache_en_cours DROP CONSTRAINT CK_EN_COURS_STATUT;

ALTER TABLE Tache_appartenant_a_liste DROP CONSTRAINT FK_TACHELISTE_REFTACHE;
ALTER TABLE Tache_appartenant_a_liste DROP CONSTRAINT FK_TACHELISTE_REFLISTE;
ALTER TABLE Travaille DROP CONSTRAINT FK_TRAVAILLE_REFUTILISATEUR;
ALTER TABLE Travaille DROP CONSTRAINT FK_TRAVAILLE_PROJET;

ALTER TABLE Score_categorie_tache DROP CONSTRAINT CK_TERMINE;
ALTER TABLE Score_categorie_tache DROP CONSTRAINT FK_TACHE_CATEGORIE_sc;
ALTER TABLE Utilisateur DROP CONSTRAINT FK_USR_PROG;


DROP VIEW Taches;
DROP TABLE Comporte;
DROP TABLE Contient;
DROP TABLE Depend_de;
DROP TABLE Est_assigne;
DROP TABLE Liste_tache;
DROP TABLE Periodicite;
DROP TABLE Score_categorie_tache;
DROP TABLE Tache_fini;
DROP TABLE Tache_en_cours;
DROP TABLE Tache;
DROP TABLE Tache_appartenant_a_liste;
DROP TABLE Travaille;
DROP TABLE Programme_de_score;
DROP TABLE Utilisateur;
DROP TABLE Categorie;
DROP TABLE Projet;

